// Generated by gencpp from file ygc/GroupBearing.msg
// DO NOT EDIT!


#ifndef YGC_MESSAGE_GROUPBEARING_H
#define YGC_MESSAGE_GROUPBEARING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ygc/Bearing2D.h>

namespace ygc
{
template <class ContainerAllocator>
struct GroupBearing_
{
  typedef GroupBearing_<ContainerAllocator> Type;

  GroupBearing_()
    : bearings()  {
    }
  GroupBearing_(const ContainerAllocator& _alloc)
    : bearings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ygc::Bearing2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ygc::Bearing2D_<ContainerAllocator> >::other >  _bearings_type;
  _bearings_type bearings;




  typedef boost::shared_ptr< ::ygc::GroupBearing_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ygc::GroupBearing_<ContainerAllocator> const> ConstPtr;

}; // struct GroupBearing_

typedef ::ygc::GroupBearing_<std::allocator<void> > GroupBearing;

typedef boost::shared_ptr< ::ygc::GroupBearing > GroupBearingPtr;
typedef boost::shared_ptr< ::ygc::GroupBearing const> GroupBearingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ygc::GroupBearing_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ygc::GroupBearing_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ygc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'ygc': ['/home/ros16/WorkSpace/bearing_ws/src/ygc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ygc::GroupBearing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ygc::GroupBearing_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ygc::GroupBearing_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ygc::GroupBearing_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ygc::GroupBearing_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ygc::GroupBearing_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ygc::GroupBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f03b323f78db40d62b3828c934a95919";
  }

  static const char* value(const ::ygc::GroupBearing_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf03b323f78db40d6ULL;
  static const uint64_t static_value2 = 0x2b3828c934a95919ULL;
};

template<class ContainerAllocator>
struct DataType< ::ygc::GroupBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ygc/GroupBearing";
  }

  static const char* value(const ::ygc::GroupBearing_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ygc::GroupBearing_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Bearing2D[] bearings\n\
\n\
================================================================================\n\
MSG: ygc/Bearing2D\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::ygc::GroupBearing_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ygc::GroupBearing_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroupBearing_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ygc::GroupBearing_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ygc::GroupBearing_<ContainerAllocator>& v)
  {
    s << indent << "bearings[]" << std::endl;
    for (size_t i = 0; i < v.bearings.size(); ++i)
    {
      s << indent << "  bearings[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ygc::Bearing2D_<ContainerAllocator> >::stream(s, indent + "    ", v.bearings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YGC_MESSAGE_GROUPBEARING_H
