set(_CATKIN_CURRENT_PACKAGE "formation")
set(formation_VERSION "0.0.0")
set(formation_MAINTAINER "nubot <yuyangguang11@nudt.edu.cn>")
set(formation_PACKAGE_FORMAT "1")
set(formation_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "std_srvs" "mavros" "mavros_msgs" "sensor_msgs" "message_generation" "dynamic_reconfigure" "cmake_modules" "ygc")
set(formation_BUILD_EXPORT_DEPENDS "cmake_modules" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "mavros" "mavros_msgs" "sensor_msgs" "ygc")
set(formation_BUILDTOOL_DEPENDS "catkin")
set(formation_BUILDTOOL_EXPORT_DEPENDS )
set(formation_EXEC_DEPENDS "cmake_modules" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "mavros" "mavros_msgs" "sensor_msgs" "ygc")
set(formation_RUN_DEPENDS "cmake_modules" "roscpp" "rospy" "std_msgs" "std_srvs" "message_generation" "dynamic_reconfigure" "mavros" "mavros_msgs" "sensor_msgs" "ygc")
set(formation_TEST_DEPENDS )
set(formation_DOC_DEPENDS )
set(formation_DEPRECATED "")